--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Missouriiii/BlossomBridge
build-by-default: true
branches:
- main
projects:
  BlossomBridge:
    path: ""
    libs:
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: ^0.1.0
...
